docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: intro.md
    - Reference:
        - "Memory Manager": memory-manager.md
        - "Memory Objects": memory-objects.md
site_name: zend-memory
site_description: "Manage data in an environment with limited memory"
repo_url: 'https://github.com/zendframework/zend-memory'
